spring:
  profiles:
    active: local
  main:
    web-application-type: reactive
  data:
    mongodb:
      uri: mongodb+srv://moebius:highbal1!@moebius-beta-zbd8m.mongodb.net/test?retryWrites=true&streamType=netty
      database: moebius
  thymeleaf:
    reactive:
      max-chunk-size: 8192

server:
  port: 80
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/moebius/tomcat
logging:
  level:
    root: INFO
    com.moebius: DEBUG
  file: moebius.log
  path: /var/log/moebius

logging.group.org.springframework.web.handler-mappings:
  - 'org.springframework.web.servlet.mvc.method'
  - 'org.springframework.web.reactive.result.method'
  - 'org.springframework.web.reactive.function.server.support'

logging.level.org.springframework.web.handler-mappings: TRACE
