spring:
  profiles:
    active: local

logging:
  level:
    root: INFO
    com.moebius: DEBUG
  file: /var/log/moebius/app.log

moebius:
  protocol: http
  host: 127.0.0.1
  web-security:
    all: /,
      /csrf,
      /static/**,
      /v2/api-docs,
      /swagger,
      /swagger-ui.html,
      /swagger-resources/**,
      /webjars/**,
      /api/member/**,
      /api/members/**,
      /api/orders/**,
      /login
    admin: /admin,
      /api/markets/**
    member: /api/stoplosses/**,
      /api/api-keys/**