spring:
  profiles:
    active: develop

logging:
  level:
    root: INFO
    com.moebius: DEBUG
  file: /var/log/moebius/app.log

moebius:
  protocol: http
  host: api-dev.cryptoboxglobal.com
  web-security:
    all: /,
      /csrf,
      /static/*,
      /v2/api-docs,
      /swagger,
      /swagger-ui.html,
      /swagger-resources/**,
      /webjars/**,
      /api/member/**,
      /api/members/**,
      /login
    admin: /admin
    member: /api/stoplosses/**,
      /api/api-keys/**

reactor:
  netty:
    http:
      server:
        AccessLog: INFO
