spring:
  profiles:
    active: production
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    com.moebius: INFO
  file: /var/log/moebius/app.log

moebius:
  protocol: http
  host: api.hashmainpro.com
  web-security:
    all: /,
      /csrf,
      /static/**,
      /member/**,
      /members/**,
      /login
    admin: /admin,
      /markets/**
    member: /stoplosses/**,
      /api-keys/**,
      /orders/**

reactor:
  netty:
    http:
      server:
        AccessLog: INFO