spring:
  profiles:
    active: production

server:
  port: 80
  tomcat:
    basedir: /var/log/moebius
    accesslog:
      enabled: true
      directory: tomcat
  error:
    whitelabel:
      enabled: false
logging:
  level:
    root: INFO
    com.moebius: INFO
  file: /var/log/moebius/app.log

moebius:
  protocol: http
  host: 52.79.86.26
