spring:
  profiles:
    active: production

logging:
  level:
    root: INFO
    com.moebius: INFO
  file: /var/log/moebius/app.log

moebius:
  protocol: http
  host: 52.79.86.26

reactor:
  netty:
    http:
      server:
        AccessLog: INFO
