spring:
  profiles:
    active: develop

logging:
  level:
    root: INFO
    com.moebius: DEBUG
  file: /var/log/moebius/app.log

moebius:
  protocol: http
  host: api-dev.cryptoboxglobal.com

reactor:
  netty:
    http:
      server:
        AccessLog: INFO
