spring:
  profiles:
    active: production
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    com.moebius: INFO
  file: /var/log/moebius/app.log

moebius:
  protocol: http
  host: api.cryptoboxglobal.com
  web-security:
    all: /,
      /csrf,
      /static/*,
      /api/member/**,
      /api/members/**,
      /login
    admin: /admin
    member: /api/stoplosses/**,
      /api/api-keys/**

reactor:
  netty:
    http:
      server:
        AccessLog: INFO