spring:
  profiles:
    active: develop

logging:
  level:
    root: INFO
    com.moebius: DEBUG
  file: /var/log/moebius/app.log

moebius:
  protocol: http
  host: dev-api.hashmainpro.com
  web-security:
    all: /,
      /csrf,
      /static/**,
      /actuator/**,
      /v2/api-docs,
      /swagger-ui/**,
      /swagger-resources/**,
      /webjars/**,
      /member/**,
      /members/**,
      /markets/**,
      /login
    admin: /admin
    member: /stoplosses/**,
      /api-keys/**,
      /orders/**

reactor:
  netty:
    http:
      server:
        AccessLog: INFO
