spring:
  profiles:
    active: local
  main:
    web-application-type: reactive
  data:
    mongodb:
      uri: mongodb+srv://moebius:highbal1!@mongodb-rs.cryptoboxglobal.com/?retryWrites=true&streamType=netty&readPreference=secondary&ssl=false # TODO : Change to use ssl
      database: moebius
    elasticsearch:
      cluster-nodes: http://internal-moebius-es-1636081679.ap-northeast-2.elb.amazonaws.com
  thymeleaf:
    reactive:
      max-chunk-size: 8192
  mail:
    host: smtp.gmail.com
    port: 587
    username: cryptobox.master@gmail.com
    password: highbal1!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

exchange:
  upbit:
    websocket:
      uri: wss://api.upbit.com/websocket/v1
    rest:
      public-uri: https://api.upbit.com/
      secret-uri: https://crix-api-endpoint.upbit.com/v1/crix/
      asset: v1/accounts
      market: v1/market/all

server:
  port: 80

logging.group.org.springframework.web.handler-mappings:
  - 'org.springframework.web.reactive.result.method'
  - 'org.springframework.web.reactive.function.server.support'

logging.level.org.springframework.web.handler-mappings: TRACE