spring:
  profiles:
    active: production

server:
  port: 80
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/moebius/tomcat
logging:
  level:
    root: INFO
    com.moebius: INFO
  file: /var/log/moebius/app.log

moebius:
  host: 52.79.86.26
