spring:
  profiles:
    active: local

server:
  port: 80
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/moebius/tomcat
logging:
  level:
    root: INFO
    com.moebius: DEBUG
  file: /var/log/moebius/app.log

moebius:
  protocol: http
  host: 127.0.0.1
