

exchange:
  upbit:
    websocket:
      uri: wss://api.upbit.com/websocket/v1
    rest:
      public-uri: https://api.upbit.com/
      secret-uri: https://crix-api-endpoint.upbit.com/v1/crix/
      asset: v1/accounts
spring:
  data:
    elasticsearch:
      cluster-nodes: http://localhost:9200