spring:
  data:
    elasticsearch:
      cluster-nodes: http://internal-moebius-es-1636081679.ap-northeast-2.elb.amazonaws.com
      properties:
        username: moebius
        password: highbal1!
    mongodb:
      uri: mongodb+srv://moebius:highbal1!@mongodb-rs.cryptoboxglobal.com/?retryWrites=true&streamType=netty&readPreference=secondary&ssl=false # TODO : Change to use ssl
      database: moebius
  kafka:
    bootstrap-servers: kafka.cryptoboxglobal.com:9092
    client-id: moebius
    producer:
      client-id: moebius-producer
      acks: all
    jaas:
      login-module: org.apache.kafka.common.security.plain.PlainLoginModule
      options:
        username: moebius
        password: VVbRzWYK4OHE

exchange:
  upbit:
    websocket:
      uri: wss://api.upbit.com/websocket/v1
    rest:
      public-uri: https://api.upbit.com/
      secret-uri: https://crix-api-endpoint.upbit.com/v1/crix/
      asset: v1/accounts

logging:
  level:
    root: INFO
    com.moebius: INFO
  file: /var/log/moebius/tracker.log
