spring:
  profiles:
    active: local

upbit:
  accessKey: 0wtwaQBpORWbd1pjvtM4e47wQxcygDEgIMYNz7DK
  secretKey: xVnuCcZrxayeShHyodcQNWbmNjcl2XuCqTiLLCN0
  uriInfo:
    openedHost: https://api.upbit.com/
    secretHost: https://crix-api-endpoint.upbit.com/v1/crix/
    asset: v1/accounts
    order:
